### ISSUE TITLE
Should express features fastify doesn't have be turned off?

### ISSUE THREAD

**Issue by dougwilson** [abenhamdine/frameworks-benchmark#3]
Just a general question I usually see in benchmarks: should all the on-by-default features in Express that are not implemented in Fastify be turned off in the Express example? I'm sure this won't make Express faster, because there is a lot you can't turn off, but things like the ETag generation usually takes a perf hit, and AFAIK Fastify doesn't implement ETag OOB. `app.disable('etag')` disables that feature in Express, for example.

**Comment by cagataycali** [comment]
You solve this problem in the other directory. It can be turned off here.

**Comment by abenhamdine** [comment]
Thanks guys for all your time & useful advices !
This repo was just a quick & dirty benchmark, I'm gonna probably close it once there will be different response sizes tested in https://github.com/fastify/fastify-benchmarks, so there will be no need to react here.
Thx again !
